from PIL import Image
import os

print("新しい敵の画像を生成します...")
assets_path = 'assets'
os.makedirs(assets_path, exist_ok=True)

# 色の定義
BG = (0,0,0,0); SK = (34,139,34,255); SD = (0,100,0,255); EY = (255,0,0,255); PU = (0,0,0,255)
CL = (160,82,45,255); OT = (200,200,200,255); GL = (112,128,144,255); GD = (47,79,79,255)

# オークのピクセルデータ (48x48)
orc_data = [
    [BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SK,SK,SD,SD,SK,SK,SK,SK,SK,SK,SK,SD,SD,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SK,SK,SK,SD,SD,SD,SD,SK,SK,EY,PU,EY,SK,SK,SD,SD,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SK,SK,SD,SD,SD,SK,EY,EY,PU,EY,EY,EY,SK,SK,SD,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],

    [BG,BG,BG,BG,SK,SK,SD,SK,EY,EY,PU,PU,PU,PU,PU,EY,EY,SK,SK,SD,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SK,SK,SD,SK,EY,PU,PU,PU,PU,PU,PU,PU,EY,SK,SK,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SK,SK,SK,SD,EY,PU,PU,PU,PU,PU,PU,PU,EY,SD,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SK,SK,SK,SD,SD,EY,EY,EY,EY,EY,EY,EY,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SK,SK,SK,SK,SD,SD,SD,SD,SD,SD,SD,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SK,SK,SK,OT,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,OT,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,OT,OT,OT,SK,SK,SD,SD,SD,SD,SK,SK,OT,OT,OT,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SK,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,CL,CL,SK,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,SK,CL,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,CL,CL,CL,SK,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SK,CL,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,CL,CL,CL,SK,CL,CL,CL,SD,SD,SD,SD,SD,SD,CL,CL,SK,CL,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,CL,CL,CL,SK,CL,CL,CL,SD,BG,BG,BG,BG,SD,CL,CL,SK,CL,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,CL,CL,CL,SK,CL,CL,SD,BG,BG,BG,BG,BG,BG,SD,CL,SK,CL,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,CL,CL,SK,CL,CL,SD,BG,BG,BG,BG,BG,BG,SD,CL,SK,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,CL,CL,SK,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SK,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,CL,CL,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,CL,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,CL,CL,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,CL,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,CL,SD,SD,SD,BG,BG,BG,BG,BG,BG,SD,SD,SD,CL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
]

# ゴーレムのピクセルデータ (96x96) - 4タイル分
golem_data = [
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,GL,GL,GL,GL,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG],
    [BG,BG,BG,BG,GL,GL,GL,GD,GD,GD,GD,GD,GD,GD,GL,GL,EY,PU,EY,GL,GL,GL,GL,GL,GL,GL,EY,PU,EY,GL,GD,GD,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG],
    [BG,BG,BG,GL,GL,GL,GD,GD,GD,GD,GD,GD,GD,GD,GL,EY,EY,PU,EY,EY,GL,GL,GL,GL,EY,EY,PU,EY,EY,GL,GD,GD,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG],

    [BG,BG,BG,GL,GL,GD,GD,GD,GD,GD,GD,GD,GD,GD,GL,EY,PU,PU,PU,EY,GL,GL,GL,GL,EY,PU,PU,PU,EY,GL,GD,GD,GD,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG],
    [BG,BG,BG,GL,GL,GD,GD,GD,GD,GD,GD,GD,GD,GD,GL,EY,EY,EY,EY,EY,GL,GL,GL,GL,EY,EY,EY,EY,EY,GL,GD,GD,GD,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG],
    [BG,BG,BG,GL,GL,GL,GD,GD,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GD,GD,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG],
    [BG,BG,BG,GL,GL,GL,GL,GD,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GD,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG],

    [BG,BG,BG,BG,GL,GL,GL,GL,GL,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GD,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,GL,GD,GD,GD,GL,GL,GL,GL,GL,PU,PU,GL,GL,GL,GL,GL,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,GL,GD,GD,GD,GL,GL,PU,PU,PU,PU,PU,PU,GL,GL,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,GL,GL,GD,GD,GD,PU,PU,PU,PU,PU,PU,PU,PU,GD,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GD,GD,PU,PU,PU,PU,PU,PU,PU,PU,GD,GD,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG],

    [BG,GL,GL,GL,GL,GL,GL,GL,CL,CL,CL,CL,GL,GL,GL,GD,PU,PU,PU,PU,PU,PU,PU,PU,GD,GL,GL,GL,CL,CL,CL,CL,GL,GL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG],
    [BG,GL,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GD,PU,PU,PU,PU,PU,GD,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GD,GD,GD,GD,GD,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,GL,GL,CL,CL,CL,GD,GD,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,GD,GD,CL,CL,CL,CL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,GL,GL,CL,CL,GD,GD,GD,GD,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,GL,GL,CL,CL,CL,CL,CL,GD,GD,GD,GD,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],

    [BG,BG,GL,GL,CL,CL,GD,GD,GD,GD,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,GD,GD,GD,GD,CL,CL,CL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,GL,GL,CL,CL,CL,GD,GD,GD,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,GD,GD,GD,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,GL,GL,CL,CL,CL,GD,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,GD,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,BG,BG,GL,GL,GL,GL,CL,CL,CL,CL,CL,CL,CL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,GL,GL,GL,CL,CL,CL,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,GL,GL,GL,CL,CL,CL,CL,CL,CL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,GL,GL,GL,GL,CL,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,CL,CL,CL,CL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,CL,CL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,CL,CL,CL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],

    [BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,CL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,CL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,GL,GL,GL,GL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
]


def create_image_from_data(data, filename):
    height = len(data); width = len(data[0])
    img = Image.new('RGBA', (width, height))
    for y in range(height):
        for x in range(width):
            img.putpixel((x, y), data[y][x])
    filepath = os.path.join(assets_path, filename)
    img.save(filepath)
    print(f"'{filepath}' を生成しました。")

create_image_from_data(orc_data, "orc.png")
create_image_from_data(golem_data, "golem.png")

print("画像の生成が完了しました。")