# このプログラムを実行するには、Pillowライブラリが必要です
# ターミナルで pip install Pillow を実行してください
from PIL import Image
import os

print("ポッチの画像を生成します...")

# 保存先フォルダを作成
assets_path = 'assets'
os.makedirs(assets_path, exist_ok=True)

# 色の定義 (R, G, B, A) Aは透明度(0=透明, 255=不透明)
BG = (0, 0, 0, 0)      # 背景 (透明)
SL = (135, 206, 250, 255) # スライム本体 (SkyBlue)
SD = (70, 130, 180, 255)  # 影 (SteelBlue)
EY = (0, 0, 0, 255)       # 目 (黒)
HT = (139, 69, 19, 255)   # 帽子 (SaddleBrown)
ST = (255, 255, 0, 255)   # 星 (Yellow)

# ポッチ1のピクセルデータ (48x48)
pocchi_1_data = [
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SL,SL,SL,SL,SL,SL,EY,EY,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,EY,EY,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,EY,EY,EY,EY,EY,SL,SL,SL,SL,SL,ST,SL,SL,SL,SL,SL,EY,EY,EY,EY,EY,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,EY,EY,EY,EY,EY,EY,SL,SL,SL,ST,ST,ST,SL,SL,SL,SL,EY,EY,EY,EY,EY,EY,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,EY,EY,EY,EY,EY,EY,SL,SL,ST,ST,ST,ST,ST,SL,SL,SL,EY,EY,EY,EY,EY,EY,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,EY,EY,EY,EY,SL,SL,SL,ST,ST,ST,ST,ST,SL,SL,SL,SL,EY,EY,EY,EY,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,ST,ST,ST,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
]

# ポッチ2のピクセルデータ
pocchi_2_data = [
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,HT,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SL,SL,SL,SL,SL,EY,EY,SL,SL,SL,SL,SL,ST,SL,SL,SL,SL,SL,SL,EY,EY,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,EY,EY,EY,EY,SL,SL,SL,ST,ST,ST,SL,SL,SL,SL,SL,EY,EY,EY,EY,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,EY,EY,EY,EY,SL,SL,ST,ST,ST,ST,ST,SL,SL,SL,SL,EY,EY,EY,EY,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,ST,ST,ST,ST,ST,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SL,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
]


def create_image_from_data(data, filename):
    """ピクセルデータのリストから画像を生成して保存する関数"""
    # 画像のサイズを取得
    height = len(data)
    width = len(data[0])
    
    # RGBAモードで新しい画像を作成
    img = Image.new('RGBA', (width, height))
    
    # 1ピクセルずつ色を書き込む
    for y in range(height):
        for x in range(width):
            img.putpixel((x, y), data[y][x])
            
    # ファイルに保存
    filepath = os.path.join(assets_path, filename)
    img.save(filepath)
    print(f"'{filepath}' を生成しました。")

# 2枚の画像を生成
create_image_from_data(pocchi_1_data, "pocchi_1.png")
create_image_from_data(pocchi_2_data, "pocchi_2.png")

print("画像の生成が完了しました。")