# このプログラムを実行するには、Pillowライブラリが必要です
# ターミナルで pip install Pillow を実行してください
from PIL import Image
import os

print("ゴブリンの画像を生成します...")

# 保存先フォルダを作成
assets_path = 'assets'
os.makedirs(assets_path, exist_ok=True)

# 色の定義 (R, G, B, A) Aは透明度(0=透明, 255=不透明)
BG = (0, 0, 0, 0)      # 背景 (透明)
SK = (50, 150, 50, 255)   # 肌 (緑)
SD = (30, 100, 30, 255)   # 影
EY = (255, 255, 0, 255)   # 目 (黄色)
PU = (0, 0, 0, 255)       # 瞳 (黒)
CL = (139, 69, 19, 255)   # 服 (茶色)
OT = (200, 200, 200, 255) # その他（牙など）

# ゴブリンのピクセルデータ (48x48) - 1フレームのみ
goblin_data = [
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SD,SD,SK,SK,SK,SK,SK,SK,SK,SK,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SD,SD,SD,SD,SK,SK,SK,SK,SK,SK,SK,SK,SD,SD,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,SK,SK,SK,SD,SD,SD,SD,SD,SK,SK,EY,EY,PU,PU,PU,EY,EY,SK,SD,SD,SD,SD,SD,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SK,SD,SD,SD,SD,SK,EY,EY,PU,EY,EY,PU,PU,PU,EY,EY,PU,EY,EY,SD,SD,SD,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SK,SD,SD,SD,EY,EY,PU,EY,EY,PU,PU,PU,PU,PU,PU,PU,PU,EY,EY,PU,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SK,SK,SD,SD,EY,EY,PU,EY,EY,PU,PU,PU,PU,PU,PU,PU,PU,PU,EY,EY,PU,EY,EY,SD,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SD,EY,EY,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,EY,EY,SD,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SD,SD,EY,EY,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,EY,EY,SD,SD,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SD,SD,EY,EY,PU,PU,PU,PU,PU,PU,PU,PU,PU,PU,EY,EY,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],

    [BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SK,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,SK,OT,SK,SK,SK,SK,SK,OT,SK,SK,SK,SK,SK,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SK,SK,OT,OT,OT,SK,SK,SK,SK,SK,SK,SK,SK,SK,OT,OT,OT,SK,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SK,SK,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SK,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SK,SD,SD,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SK,SK,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SK,SD,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SD,SD,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SD,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SD,SD,SD,SD,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SD,SD,BG,BG,SD,SD,SD,CL,CL,CL,CL,CL,CL,CL,CL,CL,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SD,CL,CL,CL,CL,CL,CL,CL,CL,SD,SD,BG,BG,BG,BG,BG,BG,SD,SD,CL,CL,CL,CL,CL,CL,CL,CL,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SK,SD,SD,CL,CL,CL,CL,CL,CL,CL,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,CL,CL,CL,CL,CL,CL,SD,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SK,SD,SD,CL,CL,CL,CL,CL,CL,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,CL,CL,CL,CL,CL,SD,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SK,SD,SD,CL,CL,CL,CL,CL,CL,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,CL,CL,CL,CL,CL,SD,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SK,SD,SD,SD,CL,CL,CL,CL,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,CL,CL,CL,SD,SD,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SK,SD,SD,SD,CL,CL,CL,CL,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,CL,CL,CL,SD,SD,SD,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,SK,SK,SD,SD,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,SK,SK,SD,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,SK,SK,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,BG,BG,BG,BG,BG,BG,BG,BG,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
    [BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,SK,SK,SD,SD,SD,SD,SD,SD,SD,SD,SD,SD,SK,SK,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG,BG],
]

def create_image_from_data(data, filename):
    """ピクセルデータのリストから画像を生成して保存する関数"""
    height = len(data)
    width = len(data[0])
    img = Image.new('RGBA', (width, height))
    for y in range(height):
        for x in range(width):
            img.putpixel((x, y), data[y][x])
    filepath = os.path.join(assets_path, filename)
    img.save(filepath)
    print(f"'{filepath}' を生成しました。")

# ゴブリン画像を生成
create_image_from_data(goblin_data, "goblin.png")

print("画像の生成が完了しました。")